<?php

namespace Insider\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getGamesByTour($tour = null)
    {
        $qb = $this->createQueryBuilder('g')
            ->addSelect('l')
            ->addSelect('r')
            ->leftJoin('g.home', 'l')
            ->leftJoin('g.guest', 'r')
        ;

        if (null !== $tour) {
            $qb
                ->andWhere('g.tour = :tour')
                ->setParameter('tour', $tour)
            ;
        }

        return $qb->getQuery()->execute();
    }

    public function getMaxTour()
    {
        return $this->createQueryBuilder('g')
            ->select('g.tour')
            ->orderBy('g.tour', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }
}
