<?php

namespace Insider\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getGamesByTour($tour)
    {
        return $this->createQueryBuilder('g')
            ->addSelect('b')
            ->addSelect('r')
            ->andWhere('g.tour = :tour')
            ->setParameter('tour', $tour)
            ->leftJoin('g.blue', 'b')
            ->leftJoin('g.red', 'r')
            ->getQuery()
            ->execute()
        ;
    }
}
