<?php

namespace Insider\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function getLeagueDataByTour($tour)
    {
        return $this->createQueryBuilder('t')
            ->addSelect('hg')
            ->addSelect('gg')
            ->leftJoin('t.homeGames', 'hg')
            ->leftJoin('t.guestGames', 'gg')
            ->orWhere('hg.tour <= :tour')
            ->orWhere('gg.tour <= :tour')
            ->setParameter('tour', $tour)
            ->groupBy('t.id')
            ->getQuery()
            ->execute()
        ;
    }
}
